//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATOS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DISCOCENTROHUARCAYAEntities : DbContext
    {
        public DISCOCENTROHUARCAYAEntities()
            : base("name=DISCOCENTROHUARCAYAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Detalle_Proforma> Detalle_Proforma { get; set; }
        public virtual DbSet<Evento> Evento { get; set; }
        public virtual DbSet<Evento_Items> Evento_Items { get; set; }
        public virtual DbSet<Items> Items { get; set; }
        public virtual DbSet<Proforma> Proforma { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    
        public virtual ObjectResult<Nullable<int>> Validar_Usuario(string usuario, string contraseña)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var contraseñaParameter = contraseña != null ?
                new ObjectParameter("contraseña", contraseña) :
                new ObjectParameter("contraseña", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Validar_Usuario", usuarioParameter, contraseñaParameter);
        }
    }
}
