//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Proforma
    {
        public int idDetalleProforma { get; set; }
        public Nullable<int> idProforma { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<double> precio { get; set; }
        public string ubicacion { get; set; }
    
        public virtual Proforma Proforma { get; set; }
    }
}
